### ISSUE TITLE
Can boudrate

### ISSUE THREAD

**Issue by Duck-Development** [RoboMasterS1Challenge/robomaster_s1_can_hack#4]
What is the can boudrate? I did not find it in the code. Is it 1 or 2 mega boud

**Comment by JohnieBraaf** [comment]
it 1 mbit

**Comment by JohnieBraaf** [comment]
you can find it by opening the stm cube project and checking the can bus timing.

With periphials clock is at 54mhz this translates to:
can.init(mode=pyb.CAN.NORMAL, extframe=False, prescaler=3, sjw=1, bs1=15, bs2=2, auto_restart=True) # 1mbps @216Mhz

**Comment by Duck-Development** [comment]
Than you
